# SGS 
USE_PKGBUILD=1

include /usr/local/share/luggage/luggage.make

TITLE=SGS_Printer_Athletics_HP_LaserJet_2300
REVERSE_DOMAIN=org.seattlegirlsschool
PAYLOAD=pack-script-postinstall
PACKAGE_VERSION=2015.08.09.13.01
