# SGS 
USE_PKGBUILD=1

include /usr/local/share/luggage/luggage.make

TITLE=SGS_Printer_Art_Room_HP_LaserJet_4300
REVERSE_DOMAIN=org.seattlegirlsschool
PAYLOAD=pack-script-postinstall
PACKAGE_VERSION=2015.08.18.13.37
