# SGS 
USE_PKGBUILD=1

include /usr/local/share/luggage/luggage.make

TITLE=SGS_Printer_CMR_HP_LaserJet_4000
REVERSE_DOMAIN=org.seattlegirlsschool
PAYLOAD=pack-script-postinstall
PACKAGE_VERSION=2015.08.27.18.05
