REM @ECHO OFF

\\SHAKTI\Clients\Setup\setup.exe /s SHAKTI

REM NET USE * /delete /y

REM

IFMEMBER "Tech Group"
IF ERRORLEVEL 1 GOTO TECH

IFMEMBER "Domain Admins"
IF ERRORLEVEL 1 GOTO TECH

:RETURNTECH

IFMEMBER "Academics Group
IF ERRORLEVEL 1 GOTO ACADEMICS

:RETURNACADEMICS

IFMEMBER "Admissions Group"
IF ERRORLEVEL 1 GOTO ADMISSIONS

:RETURNADMISSIONS

IFMEMBER "Business Group"
IF ERRORLEVEL 1 GOTO BUSINESS

:RETURNBUSINESS

IFMEMBER "Development Group"
IF ERRORLEVEL 1 GOTO DEVELOPMENT

:RETURNDEVELOPMENT

rem IFMEMBER "Faculty Group"
rem IF ERRORLEVEL 1 GOTO FACULTY

rem :RETURNFACULTY

REM IFMEMBER "Volunteer Group"
REM IF ERRORLEVEL 1 GOTO PUBLIC

IFMEMBER "Leadership Group"
IF ERRORLEVEL 1 NET USE L: \\READYNAS\leadership

IFMEMBER "Domain Users"
IF ERRORLEVEL 1 GOTO PUBLIC

GOTO END

:TECH

REM NET USE X: \\READYNAS\academics
REM NET USE M: \\READYNAS\admissions
REM NET USE N: \\READYNAS\business

NET USE Q: \\SHAKTI\quickbooks

REM NET USE V: \\READYNAS\development
REM NET USE T: \\READYNAS\teachers
REM NET USE L: \\READYNAS\leadership

REM NET USE U: \\READYNAS\users
REM NET USE Z: \\READYNAS\tech

REM NET USE R: \\READYNAS\grade5
REM NET USE S: \\READYNAS\grade6
REM NET USE W: \\READYNAS\grade7
REM NET USE Y: \\READYNAS\grade8


GOTO RETURNTECH

:ACADEMICS

REM NET USE X: \\READYNAS\academics

GOTO RETURNACADEMICS

REM

:ADMISSIONS

REM NET USE M: \\READYNAS\admissions

GOTO RETURNADMISSIONS

:BUSINESS

REM NET USE N: \\READYNAS\business
REM NET USE Q: \\SHAKTI\quickbooks

GOTO RETURNBUSINESS

:DEVELOPMENT

REM NET USE V: \\READYNAS\development

GOTO RETURNDEVELOPMENT

rem :FACULTY

rem NET USE T: \\READYNAS\teachers

rem GOTO RETURNFACULTY

:PUBLIC

REM NET USE P: \\READYNAS\public

GOTO END

:END
