# SGS 
USE_PKGBUILD=1

include /usr/local/share/luggage/luggage.make

TITLE=SGS_Printer_7th_Grade_East_HP_LaserJet_1320
REVERSE_DOMAIN=org.seattlegirlsschool
PAYLOAD=pack-script-postinstall
PACKAGE_VERSION=2015.08.27.18.05
