# SGS 
USE_PKGBUILD=1

include /usr/local/share/luggage/luggage.make

TITLE=SGS_Printer_6th_Grade_Central_HP_LaserJet_4000_PCL_6
REVERSE_DOMAIN=org.seattlegirlsschool
PAYLOAD=pack-script-postinstall
PACKAGE_VERSION=2015.03.24.16.41
